# Generated by Django 5.0.4 on 2024-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_data_points_measurement_data_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Raw Data', 'Raw Data'), ('Radiance', 'Radiance'), ('Average Radiance', 'Average Radiance'), ('Text Radiance', 'Text Radiance'), ('Reflectance', 'Reflectance'), ('Average Reflectance', 'Average Reflectance'), ('Text Reflectance', 'Text Reflectance')], max_length=128),
        ),
    ]
