# Generated by Django 5.0.4 on 2024-11-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_category_options_alter_campaign_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_synced_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='last_synced_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='last_synced_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='last_synced_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='last_synced_at',
            field=models.DateTimeField(null=True),
        ),
    ]
