# Generated by Django 5.0.4 on 2024-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_invalid_proxies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
