# Generated by Django 5.0.4 on 2025-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_campaign_is_unmatched_coverage_is_unmatched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Raw Data', 'Raw Data'), ('Text Data', 'Text Data'), ('Photometry', 'Photometry'), ('Radiance', 'Radiance'), ('Average Radiance', 'Average Radiance'), ('Text Radiance', 'Text Radiance'), ('Text Average Radiance', 'Text Average Radiance'), ('Radiance Parabolic Correction', 'Radiance Parabolic Correction'), ('Text Radiance Parabolic Correction', 'Text Radiance Parabolic Correction'), ('Reflectance', 'Reflectance'), ('Average Reflectance', 'Average Reflectance'), ('Text Reflectance', 'Text Reflectance'), ('Text Average Reflectance', 'Text Average Reflectance'), ('Reflectance Parabolic Correction', 'Reflectance Parabolic Correction'), ('Text Reflectance Parabolic Correction', 'Text Reflectance Parabolic Correction')], max_length=128, unique=True),
        ),
    ]
