# Generated by Django 5.0.4 on 2025-04-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='scan_complete',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='scan_complete',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='scan_complete',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='scan_complete',
        ),
        migrations.RemoveField(
            model_name='spreadsheet',
            name='scan_complete',
        ),
    ]
