# Generated by Django 5.0.4 on 2025-04-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaign_scan_complete_coverage_scan_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplimentaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ftp_created_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_complete', models.BooleanField(default=False)),
                ('is_unmatched', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_data', to='campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
