# Generated by Django 5.0.4 on 2025-04-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_complimentarydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedCampaign',
            fields=[
            ],
            options={
                'verbose_name': 'Unmatched Campaign',
                'verbose_name_plural': 'Unmatched Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campaigns.campaign',),
        ),
        migrations.CreateModel(
            name='UnmatchedDataPoint',
            fields=[
            ],
            options={
                'verbose_name': 'Unmatched Data Point',
                'verbose_name_plural': 'Unmatched Data Points',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campaigns.datapoint',),
        ),
        migrations.CreateModel(
            name='UnmatchedMeasurement',
            fields=[
            ],
            options={
                'verbose_name': 'Unmatched Measurement',
                'verbose_name_plural': 'Unmatched Measurements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campaigns.measurement',),
        ),
    ]
