# Generated by Django 5.0.4 on 2025-10-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_remove_campaign_measuring_tool_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complimentarydata",
            options={"verbose_name_plural": "Complimentary Data"},
        ),
        migrations.AlterField(
            model_name="complimentarydata",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complementary_data",
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="complimentarydata",
            name="data_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complementary_data",
                to="campaigns.datapoint",
            ),
        ),
    ]
