# Generated by Django 5.0.4 on 2024-06-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Province',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='city',
            new_name='province',
        ),
    ]
