# Generated by Django 5.0.4 on 2024-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_district_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('name', 'province'), name='unique_district'),
        ),
    ]
