# Generated by Django 5.0.4 on 2024-05-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='data_points',
            new_name='data_point',
        ),
    ]
