# Generated by Django 5.0.4 on 2024-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ftp_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='ftp_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='ftp_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ftp_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='ftp_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
