# Generated by Django 5.0.4 on 2024-11-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_last_synced_at_coverage_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coverage',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
    ]
