# Generated by Django 5.0.4 on 2025-04-05 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_campaign_description_and_more'),
        ('places', '0006_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.district'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='measuring_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.measuringtool'),
        ),
    ]
