# Generated by Django 5.0.4 on 2025-04-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_campaign_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_unmatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coverage',
            name='is_unmatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='is_unmatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='is_unmatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='is_unmatched',
            field=models.BooleanField(default=False),
        ),
    ]
