# Generated by Django 5.0.4 on 2025-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_remove_campaign_scan_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coverage',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='scan_complete',
            field=models.BooleanField(default=False),
        ),
    ]
