# Generated by Django 5.0.4 on 2025-10-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_unmatchedcampaign_unmatcheddatapoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'All Campaign',
                'verbose_name_plural': 'All Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campaigns.campaign',),
        ),
    ]
