# Generated by Django 5.0.4 on 2025-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_allcampaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('pattern', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('coverage', 'coverage'), ('campaign', 'campaign'), ('data_point', 'data_point'), ('category', 'category'), ('measurement', 'measurement')], max_length=255)),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
    ]
