# Generated by Django 5.0.4 on 2025-10-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_pathrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathrule',
            name='field_name',
        ),
    ]
