# Generated by Django 5.0.4 on 2025-10-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_remove_pathrule_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ftp_created_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_complete', models.BooleanField(default=False)),
                ('is_unmatched', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('parent_path', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AllCampaigns',
        ),
        migrations.DeleteModel(
            name='UnmatchedCampaign',
        ),
        migrations.DeleteModel(
            name='UnmatchedDataPoint',
        ),
        migrations.DeleteModel(
            name='UnmatchedMeasurement',
        ),
    ]
