# Generated by Django 5.0.4 on 2025-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_unmatchedfile_delete_allcampaigns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unmatchedfile',
            name='parent_path',
            field=models.CharField(max_length=255),
        ),
    ]
