# Generated by Django 5.0.4 on 2025-10-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_alter_unmatchedfile_parent_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmatchedfile',
            name='level',
            field=models.CharField(choices=[('coverage', 'coverage'), ('campaign', 'campaign'), ('data_point', 'data_point'), ('category', 'category'), ('measurement', 'measurement')], default='campaign', max_length=255),
            preserve_default=False,
        ),
    ]
