# Generated by Django 5.0.4 on 2025-10-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_unmatchedfile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathrule',
            name='date_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
