# Generated by Django 5.0.4 on 2025-10-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_pathrule_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
