# Generated by Django 5.0.4 on 2025-10-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_alter_datapoint_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='sheet_type',
            field=models.CharField(choices=[('Office Sheet', 'OFC'), ('Field Sheet', 'FLD'), ('Complimentary Data Sheet', 'CDS')], max_length=255),
        ),
    ]
