# Generated by Django 5.0.4 on 2025-10-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_alter_spreadsheet_sheet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathrule',
            name='level',
            field=models.CharField(choices=[('coverage', 'coverage'), ('campaign', 'campaign'), ('data_point', 'data_point'), ('category', 'category'), ('measurement', 'measurement'), ('complimentary_data', 'complimentary_data')], max_length=255),
        ),
        migrations.AlterField(
            model_name='unmatchedfile',
            name='level',
            field=models.CharField(choices=[('coverage', 'coverage'), ('campaign', 'campaign'), ('data_point', 'data_point'), ('category', 'category'), ('measurement', 'measurement'), ('complimentary_data', 'complimentary_data')], max_length=255),
        ),
    ]
