# Generated by Django 5.0.4 on 2025-10-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0029_alter_pathrule_level_alter_unmatchedfile_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['path']},
        ),
        migrations.AlterModelOptions(
            name='complimentarydata',
            options={'ordering': ['path']},
        ),
        migrations.AlterModelOptions(
            name='coverage',
            options={'ordering': ['path']},
        ),
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['path']},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['path']},
        ),
        migrations.AlterModelOptions(
            name='spreadsheet',
            options={'ordering': ['path']},
        ),
        migrations.AlterModelOptions(
            name='unmatchedfile',
            options={'ordering': ['path']},
        ),
    ]
